# -*- shell-script -*-
# ~/.zshenv

# language locale setting
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8
# default permission rwxr-xr-x
umask 022
# path settings
export PATH=/usr/X11/bin:/usr/sbin:/usr/bin:/sbin:/bin
export MANPATH=/usr/X11R6/man:/usr/share/man
# load machine specific settings
if [ -f "$HOME/.zsh/zshenv-local" ]; then
    source "$HOME/.zsh/zshenv-local"
fi
